spring.application.name=USER-SERVICE
server.port=6061

# 1. Database Connection URL
# Syntax: jdbc:postgresql://<host>:<port>/<database_name>
spring.datasource.url=jdbc:postgresql://localhost:5432/fitness_user_db

# 2. Database Credentials
spring.datasource.username=postgres
spring.datasource.password=Vikki@04

# 3. Driver Class Name (Optional in newer Spring Boot versions, but good practice)
spring.datasource.driver-class-name=org.postgresql.Driver

# 4. Hibernate / JPA Properties
# 'update' will create/update tables automatically, but NOT the database itself
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/